[package]
name = "rocksdb_sq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.21.0"
byteorder = "1.4.3"

[dev-dependencies]
tempfile = "3.5.0"
